Initial release candidate
EquitableLettersSP/ELSP pull request #26
Opened 2021-02-04 15:38 UTC by melissaroses

Initial launch of webpage

2021-02-05 12:00 UTC, johncoxon requested changes
Most of this is really good! I have a few comments I think need addressing before the commit goes through but in general congratulations are in order for everyone involved.

2021-02-05 13:42 UTC, aburrell requested changes
A few things that need to be addressed.  It looks like we need a handful of html pages to provide people links to some outward facing markdown files, as well.

2021-02-05 13:42 UTC, aburrell commented on CODE_OF_CONDUCT.md
> +This is version 1.0 of our Code of Conduct (ADD DATE AFTER ADDING LINKS).
```suggestion
This is version 1.0 of our Code of Conduct was adopted on 8 Feb 2021.
```

2021-02-05 13:42 UTC, aburrell commented on CODE_OF_CONDUCT.md
> +We as editors, reviewers, and writers pledge to follow this code of conduct in the name of our
```suggestion
We as directors, reviewers, and writers pledge to follow this code of conduct in the name of our
```

2021-02-05 13:42 UTC, aburrell commented on CODE_OF_CONDUCT.md
>  - Not adhering to the guidelines for submitters and reviews (LINK HERE).
Need to add links to those documents here, now that we have them.

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/acknowledge_receipt_of_review.md
> +Editor - your name
```suggestion
Director - your name
```

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/acknowledge_receipt_of_review.md
> +Editor
```suggestion
Director
```

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/receipt_of_submission.md
> +Editor - your name
```suggestion
Director - your name
```

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/receipt_of_submission.md
> +Editor
```suggestion
Director
```

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/requesting_review.md
> +Editor - your name
```suggestion
Director - your name
```

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/requesting_review.md
> +Editor
```suggestion
Director
```

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/return_ferpa_to_submitter.md
> +Editor - your name
```suggestion
Director - your name
```

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/return_ferpa_to_submitter.md
> +Editor
```suggestion
Director
```

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/return_review_to_submitter.md
> +Editor - your name
```suggestion
Director - your name
```

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/return_review_to_submitter.md
> +The criteria used to review your letter can be found here (link to our reviewer criteria).
Yup.

2021-02-05 13:42 UTC, aburrell commented on Email_Forms/return_review_to_submitter.md
> +Editor
```suggestion
Director
```

2021-02-05 13:42 UTC, aburrell commented on elspContact.html
> +            <p>Because you can't catch half of your own typos, let alone your unconscious bias.</p>
If it's coming off as abrasive, then yes.  I was talking with a friend when I put the project this way, and she thought that it was a good way to put it, since it basically told people that _they were making mistakes in a way similar to another type of mistake (that doesn't hurt people) that they've already acknowledged they're capable of making_.  But personal delivery and delivery of words on a screen are two completely different things.  What do you suggest that would get the same point across?

2021-02-05 13:42 UTC, aburrell commented on elspContact.html
> +            <p>In the near future, we will be accepting reference and nomination letters for review, specifically looking to address common issues introduced by unconscious biases. At this point in t
You know, you're probably right about that.  And if we get flooded with spam we can always change back.

2021-02-05 13:42 UTC, aburrell commented on elspLetterResources.html
> +                <p>We ask that all submitters to ELSP stay in accordance with FERPA laws and blackout/remove any non-directory personally identifiable information (PII) or non-directory education rec
Edited your suggestion @johncoxon to use "redact", because I think it's the most correct word and also adds a bit of alliteration.

2021-02-05 13:42 UTC, aburrell commented on index.html
> +            <p> Equitable Letters in Space Physics strives to provide a welcoming environment for people to learn and grow. We are governed by a <a href="https://github.com/EquitableLettersSP/ELSP/bl
That's a good point.  We did it this way initially because apparently having html wrap a markdown file isn't simple.  But I think this is reason enough to initially duplicate the documentation until we get that sorted.

2021-02-08 15:19 UTC, aburrell commented on Review_Resources/review_form.md
> +- Gender
```suggestion
- Gender/Orientation
```

2021-02-08 15:20 UTC, aburrell commented on Review_Resources/review_guidelines.md
> +- Gender
```suggestion
- Gender/Orientation
```

2021-02-08 15:25 UTC, aburrell commented on elspContact.html
> +            <p>Because you can't catch half of your own typos, let alone your unconscious bias.</p>
```suggestion
            <p>Here to catch typos and unconscious biases.</p>
```

2021-02-08 15:32 UTC, aburrell commented on elspSampleLetters.html
> +                        <p><a href="#" class="tooltip">Warmest Regards,<span>This greeting is typically used among close colleagues. As this is a formal letter “Sincerely” or “Best Regards” would be
```suggestion
                        <p><a href="#" class="tooltip">Warmest Regards,<span>This salutation is typically used among close colleagues. As this is a formal letter “Sincerely” or “Best Regards” would be more appropriate.</span></a></p>
```

2021-02-08 15:46 UTC, aburrell commented on index.html
> +            <p> To promote meritocracy within the international space physics community by providing resources to improve recommendation and nomination letters by reducing written manifestations of i
```suggestion
            <p> To reduce written manifestations of implicit bias by providing resources to improve recommendation and nomination letter, thus promoting meritocracy within the international space physics community.</p>
```

2021-02-08 15:47 UTC, aburrell commented on index.html
> +	      <li> Dr. MacArthur Jones Jr., Naval Research Laboratory </li>
```suggestion
	      <li> Dr. McArthur Jones Jr., Naval Research Laboratory </li>
```

2021-02-08 17:55 UTC, AJHalford commented on index.html
> +            <p> To promote meritocracy within the international space physics community by providing resources to improve recommendation and nomination letters by reducing written manifestations of i
Given that this is supposed to be our mission statement I think it should not be a list. I think a list will make it more difficult for a person to quickly read and remember what we are all about.  Ideally, a mission statement would answer the following questions: what do we do, how do we do it, whom do we do it for, and what value are we bringing. Then we would also like it to be easy to remember so people can easily tell their friends who we are, etc. So I actually think it would be good if we were able to use a more common language here. Here's a website with some great non-profit examples https://topnonprofits.com/examples/nonprofit-mission-statements/

So how about: Encouraging meritocracy (or maybe equity) within recommendation and nomination letters throughout the international space physics community. 

Or: Encouraging meritocracy within recommendation and nomination letters throughout the international space physics community by providing resources and reviews. 

I think removing implicit bias is implicit in those statements.

2021-02-08 18:02 UTC, aburrell commented on index.html
> +            <p> To promote meritocracy within the international space physics community by providing resources to improve recommendation and nomination letters by reducing written manifestations of i
I like "Encouraging meritocracy within recommendation and nomination letters throughout the international space physics community by providing resources and reviews" because it's more specific about what we do.

2021-02-08 21:06 UTC, AJHalford requested changes
The only comment is about the mission statement. I added some suggestions but happy with whatever others decide. This is something we should periodically revisit so happy with whatever as a first take.

2021-02-09 13:58 UTC, AJHalford commented on index.html
> +            <p> To promote meritocracy within the international space physics community by providing resources to improve recommendation and nomination letters by reducing written manifestations of i
I think that's a bit too long and at a much higher reading level than we need. I don't think the mission statement needs to be that specific.  - but I also think it's an okay place to start. 

Here are three examples to hopefully show where I'm coming from. 
New York Public Library: To inspire lifelong learning, advance knowledge, and strengthen our communities. (10)
Grade C. 71% reach. 13th-grade (college freshman) reading level.

Doctors without Borders (Médecins Sans Frontières): To provide lifesaving medical care to those most in need. (10)
Grade A. 100% reach. 8th-grade reading level.

March of Dimes: Leads the fight for the health of all moms and babies. (11)
Grade A. 100% reach. 3rd-grade reading level.

For comparison, the readability score for "Encouraging meritocracy within recommendation and nomination letters throughout the international space physics community by providing resources and reviews" is a graduate student or postdoc maybe? (22nd grader) 

The readability for "Encouraging equity within recommendation and nomination letters throughout the space physics community" is also a graduate student but an earlier one (19th grader)

The readability for "To encourage merit-based recommendations and nominations in space physics" is at a 15th-grade level - so undergrad... Okay, I'll stop wasting time trying to re-work this. (one last quick one - taking this last one and ending with "... nominations in the space physics community." ups the readability to 16.5. )

2021-02-22 16:12 UTC, aburrell commented on elspContact.html
> +            <p>Here to catch typos and unconscious biases.</p>
```suggestion
            <p>Helping you catch typos and unconscious biases.</p>
```

2021-02-25 16:50 UTC, aburrell commented on elspLetterResources.html
> +                <li><a target="blank" href="http://slowe.github.io/genderbias/">Gender Bias Calculator</a> - This tool is based on Schmader's 2007 study, and analyzes text for female- and male-associ
@melissaroses

2021-02-25 16:51 UTC, aburrell commented on elspLetterResources.html
> +                <li><a target="blank" href="https://www.schoolcounselor.org/asca/media/PDFs/WebinarPowerPoints/1096-2409-20-1-102.pdf">Gender and Ethnic Bias in Letters of Recommendation: Considerati
@melissaroses

2021-02-25 16:53 UTC, aburrell commented on elspSampleLetters.html
> +<!DOCTYPE html>
@melissaroses if you fixed this, could you resolve the conversation?

2021-02-25 16:53 UTC, aburrell commented on elspStudies.html
> +                    <p class="summary">The authors' study of the letters of recommendation to Houser's REU program found that letters written for students who were male, White, from research universi
@melissaroses same for the comments on this pagee.

2021-02-26 21:00 UTC, melissaroses commented on elspStudies.html
> +                    <p class="summary">The authors' study of the letters of recommendation to Houser's REU program found that letters written for students who were male, White, from research universi
I've replaced all of the problematic punctuation.

2021-02-26 21:06 UTC, melissaroses commented on elspLetterResources.html
> +                <li><a target="blank" href="https://www.uwyo.edu/registrar/ferpa/ferpa_parents.html">University of Wyoming</a></li>
I've fixed the broken link.

2021-02-26 21:20 UTC, aburrell commented on CODE_OF_CONDUCT.md
>  - Not adhering to the guidelines for submitters and reviews (LINK HERE).
Postponing this until after the webpage is live.

2021-02-26 21:20 UTC, aburrell commented on Email_Forms/return_review_to_submitter.md
> +The criteria used to review your letter can be found here (link to our reviewer criteria).
Waiting until after the webpage goes live to put a front-facing link here.

2021-02-26 21:20 UTC, aburrell commented on Submission_Resources/submission_guidelines.md
> +- [ ] Read and agree to the code of conduct (LINK).
Waiting until after the webpage goes live to put a front-facing link here.

2021-02-26 21:20 UTC, aburrell commented on CODE_OF_CONDUCT.md
>  - Not adhering to the guidelines for submitters and reviews (LINK HERE).
Waiting until after the webpage goes live to put a front-facing link here.

2021-02-26 21:23 UTC, aburrell commented on elspLetterResources.html
> +                <li><a target="blank" href="https://www.schoolcounselor.org/asca/media/PDFs/WebinarPowerPoints/1096-2409-20-1-102.pdf">Gender and Ethnic Bias in Letters of Recommendation: Considerati
Alternative link: https://www.schoolcounselor.org/getmedia/542b085a-7eda-48ba-906e-24cd3f08a03f/SIP-Racism-Bias.pdf

2021-02-26 21:23 UTC, melissaroses commented on elspLetterResources.html
> +                <li><a target="blank" href="https://www.schoolcounselor.org/asca/media/PDFs/WebinarPowerPoints/1096-2409-20-1-102.pdf">Gender and Ethnic Bias in Letters of Recommendation: Considerati
Fixed broken link

2021-02-26 21:29 UTC, aburrell approved these changes
Just went through all the changes and it looks good enough to roll out! 🐴

2021-03-06 16:48 UTC, AJHalford approved these changes

2021-03-06 16:54 UTC, johncoxon approved these changes

2021-03-06 16:54 UTC, johncoxon commented on index.html
> +	                <li>Dr. John Coxon, Southampton University</li>
```suggestion
	                <li>Dr. John Coxon, University of Southampton</li>
```

2021-03-06 16:54 UTC, johncoxon commented on CODE_OF_CONDUCT.md
> +This is version 1.0 of our Code of Conduct was adopted on 8 Feb 2021.
```suggestion
This is version 1.0 of our Code of Conduct, which was adopted on 8 Feb 2021.
```

2021-03-06 17:04 UTC, kzawdie approved these changes

2021-03-06 17:05 UTC, mjonesjr approved these changes
🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥

2021-03-06 17:07 UTC, merged